[	
	"4px"=>["4PX Worldwide Express","trackable_on_etsy"=>1],
	"abf"=>["ABF Freight","trackable_on_etsy"=>1],
	"acscourier"=>["ACS Courier","trackable_on_etsy"=>1],
	"apc"=>["APC Postal Logistics","trackable_on_etsy"=>1],
	"aeroflash"=>["AeroFlash","trackable_on_etsy"=>1],
	"afghan-post"=>["Afghan Post","trackable_on_etsy"=>0],
	"an-post"=>["An Post","trackable_on_etsy"=>1],
	"anguilla-post"=>["Anguilla Postal Service","trackable_on_etsy"=>0],
	"aramex"=>["Aramex","trackable_on_etsy"=>1],
	"asendia-uk"=>["Asendia UK","trackable_on_etsy"=>1],
	"asendia-usa"=>["Asendia USA","trackable_on_etsy"=>1],
	"australia-post"=>["Australia Post","trackable_on_etsy"=>1],
	"austrian-post"=>["Austrian Post","trackable_on_etsy"=>1],
	"austrian-post-registered"=>["Austrian Post Registered","trackable_on_etsy"=>1],
	"bh-posta"=>["BH Posta","trackable_on_etsy"=>0],
	"bahrain-post"=>["Bahrain Post","trackable_on_etsy"=>0],
	"bangladesh-post"=>["Bangladesh Post Office","trackable_on_etsy"=>0],
	"bpost"=>["Belgium Post Domestic","trackable_on_etsy"=>1],
	"bpost-international"=>["Belgium Post International","trackable_on_etsy"=>1],
	"belpost"=>["Belposhta","trackable_on_etsy"=>1],
	"bluedart"=>["Blue Dart","trackable_on_etsy"=>1],
	"botswanapost"=>["BotswanaPost","trackable_on_etsy"=>0],
	"brunei-post"=>["Brunei Postal Services","trackable_on_etsy"=>0],
	"bgpost"=>["Bulgarian Posts","trackable_on_etsy"=>1],
	"cambodia-post"=>["Cambodia Post","trackable_on_etsy"=>1],
	"canada-post"=>["Canada Post","trackable_on_etsy"=>1],
	"canpar"=>["Canpar Courier","trackable_on_etsy"=>1],
	"ceska-posta"=>["Ceska Posta","trackable_on_etsy"=>1],
	"china-ems"=>["China EMS","trackable_on_etsy"=>1],
	"china-post"=>["China Post","trackable_on_etsy"=>1],
	"chitchats"=>["Chit Chats","trackable_on_etsy"=>1],
	"chronopost-france"=>["Chronopost France","trackable_on_etsy"=>1],
	"chronopost-portugal"=>["Chronopost Portugal","trackable_on_etsy"=>1],
	"taiwan-post"=>["Chunghwa Post","trackable_on_etsy"=>1],
	"city-link"=>["City Link","trackable_on_etsy"=>1],
	"colissimo"=>["Colissimo","trackable_on_etsy"=>1],
	"collectplus"=>["Collect+","trackable_on_etsy"=>1],
	"brazil-correios"=>["Correios de Brasil","trackable_on_etsy"=>1],
	"correios-macau"=>["Correios de Macau","trackable_on_etsy"=>0],
	"portugal-ctt"=>["Correios de Portugal (CTT)","trackable_on_etsy"=>1],
	"correo-argentino"=>["Correo Argentino Domestic","trackable_on_etsy"=>1],
	"correo-argentino-intl"=>["Correo Argentino International","trackable_on_etsy"=>1],
	"correo-uruguayo"=>["Correo Uruguayo","trackable_on_etsy"=>0],
	"spain-correos-es"=>["Correos - Espana","trackable_on_etsy"=>1],
	"correos-chile"=>["Correos Chile","trackable_on_etsy"=>1],
	"correos-de-mexico"=>["Correos De Mexico","trackable_on_etsy"=>1],
	"correos-de-costa-rica"=>["Correos de Costa Rica","trackable_on_etsy"=>1],
	"correos-ecuador"=>["Correos del Ecuador","trackable_on_etsy"=>0],
	"courierpost"=>["Courier Post","trackable_on_etsy"=>1],
	"couriers-please"=>["Couriers Please","trackable_on_etsy"=>1],
	"cyprus-post"=>["Cyprus Post","trackable_on_etsy"=>1],
	"dhl-benelux"=>["DHL Benelux","trackable_on_etsy"=>1],
	"dhl"=>["DHL Express","trackable_on_etsy"=>1],
	"dhl-germany"=>["DHL Germany","trackable_on_etsy"=>1],
	"dhl-global-mail"=>["DHL Global Mail","trackable_on_etsy"=>1],
	"dhl-global-mail-asia"=>["DHL Global Mail Asia","trackable_on_etsy"=>1],
	"dhl-nl"=>["DHL Netherlands ","trackable_on_etsy"=>1],
	"dhlparcel-nl"=>["DHL Parcel NL","trackable_on_etsy"=>1],
	"dhl-poland"=>["DHL Polska","trackable_on_etsy"=>1],
	"dhl-es"=>["DHL Spain Domestic","trackable_on_etsy"=>1],
	"dpd"=>["DPD","trackable_on_etsy"=>1],
	"dpd-de"=>["DPD Germany","trackable_on_etsy"=>1],
	"dpd-poland"=>["DPD Polska","trackable_on_etsy"=>1],
	"dpd-uk"=>["DPD UK","trackable_on_etsy"=>1],
	"dtdc"=>["DTDC India","trackable_on_etsy"=>1],
	"deltec-courier"=>["Deltec Courier","trackable_on_etsy"=>1],
	"deutsch-post"=>["Deutsche Post","trackable_on_etsy"=>1],
	"directlink"=>["Direct Link","trackable_on_etsy"=>1],
	"ec-firstclass"=>["EC-Firstclass","trackable_on_etsy"=>1],
	"egypt-post"=>["Egypt Post","trackable_on_etsy"=>0],
	"el-correo"=>["El Correo","trackable_on_etsy"=>0],
	"elta-courier"=>["Elta Courier","trackable_on_etsy"=>1],
	"emirates-post"=>["Empost","trackable_on_etsy"=>1],
	"correos-bolivia"=>["Empresa de Correos de Bolivia","trackable_on_etsy"=>0],
	"estafeta"=>["Estafeta","trackable_on_etsy"=>1],
	"estes"=>["Estes","trackable_on_etsy"=>1],
	"estonian-post"=>["Estonian Post","trackable_on_etsy"=>0],
	""=>["Ethiopian Postal Service"ethiopian-post,"trackable_on_etsy"=>0],
	"evergreen"=>["Evergreen","trackable_on_etsy"=>0],
	"fastway-au"=>["Fastway Australia","trackable_on_etsy"=>1],
	"fastway-ireland"=>["Fastway Couriers","trackable_on_etsy"=>1],
	"fastway-nz"=>["Fastway New Zealand","trackable_on_etsy"=>1],
	"fastway-za"=>["Fastways Couriers South Africa","trackable_on_etsy"=>1],
	"fedex"=>["FedEx","trackable_on_etsy"=>1],
	"fedex-uk"=>["Fedex UK (Domestic)","trackable_on_etsy"=>1],
	"first-flight"=>["First Flight Couriers","trackable_on_etsy"=>1],
	""=>["Flash Courier"flash-courier,"trackable_on_etsy"=>1],
	"gati-kwe"=>["GATI-KWE","trackable_on_etsy"=>1],
	"gls"=>["GLS","trackable_on_etsy"=>1],
	"ghana-post"=>["Ghana Post","trackable_on_etsy"=>0],
	"globegistics"=>["Globegistics","trackable_on_etsy"=>1],
	"greyhound"=>["Greyhound","trackable_on_etsy"=>1],
	"guernsey-post"=>["Guernsey Post","trackable_on_etsy"=>0],
	"hay-post"=>["Hay Post","trackable_on_etsy"=>0],
	"hellenic-post"=>["Hellenic Post","trackable_on_etsy"=>0],
	"hermes"=>["Hermes","trackable_on_etsy"=>1],
	"hermes-de"=>["Hermes Germany","trackable_on_etsy"=>1],
	"hermes-it"=>["Hermes Italy","trackable_on_etsy"=>1],
	"hong-kong-post"=>["Hong Kong Post","trackable_on_etsy"=>1],
	"hrvatska-posta"=>["Hrvatska Posta","trackable_on_etsy"=>1],
	"india-post"=>["India Post","trackable_on_etsy"=>1],
	"india-post-int"=>["India Post International","trackable_on_etsy"=>1],
	"interlink-express"=>["Interlink Express","trackable_on_etsy"=>1],
	"international-seur"=>["International Seur","trackable_on_etsy"=>1],
	"ipostel"=>["Ipostel","trackable_on_etsy"=>0],
	"iran-post"=>["Iran Post","trackable_on_etsy"=>0],
	"islandspostur"=>["Islandspostur","trackable_on_etsy"=>0],
	"isle-of-man-post"=>["Isle of Man Post Office","trackable_on_etsy"=>0],
	"israel-post"=>["Israel Post","trackable_on_etsy"=>1],
	"israel-post-domestic"=>["Israel Post Domestic","trackable_on_etsy"=>1],
	"jamaica-post"=>["Jamaica Post","trackable_on_etsy"=>0],
	"japan-post"=>["Japan Post","trackable_on_etsy"=>1],
	"jersey-post"=>["Jersey Post","trackable_on_etsy"=>0],
	"jordan-post"=>["Jordan Post","trackable_on_etsy"=>0],


	"kazpost"=>["Kazpost","trackable_on_etsy"=>0],
	"kpost"=>["Korea Post","trackable_on_etsy"=>1],
	"korea-post"=>["Korea Post EMS","trackable_on_etsy"=>1],
	"kn"=>["Kuehne + Nagel","trackable_on_etsy"=>1],
	"la-poste-colissimo"=>["La Poste","trackable_on_etsy"=>1],
	"poste-monaco"=>["La Poste Monaco","trackable_on_etsy"=>0],
	"poste-tunisienne"=>["La Poste Tunisienne","trackable_on_etsy"=>0],
	"poste-senegal"=>["La Poste du Senegal","trackable_on_etsy"=>0],
	"landmark-global"=>["Landmark Global","trackable_on_etsy"=>1],
	"lasership"=>["LaserShip","trackable_on_etsy"=>1],
	"latvijas-pasts"=>["Latvijas Pasts","trackable_on_etsy"=>0],
	"libanpost"=>["LibanPost","trackable_on_etsy"=>0],
	"lietuvos-pastas"=>["Lietuvos Pastas","trackable_on_etsy"=>1],
	"mrw-spain"=>["MRW","trackable_on_etsy"=>1],
	"magyar-posta"=>["Magyar Posta","trackable_on_etsy"=>1],
	"makedonska-posta"=>["Makedonska Posta","trackable_on_etsy"=>0],
	"malaysia-post-posdaftar"=>["Malaysia Pos Daftar","trackable_on_etsy"=>1],
	"maldives-post"=>["Maldives Post","trackable_on_etsy"=>0],
	"maltapost"=>["MaltaPost","trackable_on_etsy"=>0],
	"mauritius-post"=>["Mauritius Post","trackable_on_etsy"=>0],
	"mondialrelay"=>["Mondial Relay","trackable_on_etsy"=>1],
	"mexico-multipack"=>["Multipack","trackable_on_etsy"=>1],
	"nacex-spain"=>["Nacex","trackable_on_etsy"=>1],
	"new-zealand-post"=>["New Zealand Post","trackable_on_etsy"=>1],
	"tntpost-it"=>["Nexive","trackable_on_etsy"=>1],
	"nieuwe-post-nederlandse-antillen-pna"=>["Nieuwe Post Nederlandse Antillen (PNA)","trackable_on_etsy"=>0],
	"nipost"=>["Nigerian Postal Service","trackable_on_etsy"=>1],
	"nova-poshta"=>["Nova Poshta","trackable_on_etsy"=>1],
	"oca-ar"=>["OCA","trackable_on_etsy"=>1],
	"opek"=>["OPEK","trackable_on_etsy"=>1],
	"opt"=>["OPT","trackable_on_etsy"=>0],
	"opt-nouvelle-caledonie"=>["OPT de nouvelle-Caledonie","trackable_on_etsy"=>0],
	"oman-post"=>["Oman Post","trackable_on_etsy"=>0],
	"ontrac"=>["OnTrac","trackable_on_etsy"=>1],
	"ptt-posta"=>["PTT Posta","trackable_on_etsy"=>1],
	"pakistan-post"=>["Pakistan Post","trackable_on_etsy"=>0],
	"parcel-force"=>["Parcelforce Worldwide","trackable_on_etsy"=>1],
	"poczta-polska"=>["Poczta Polska","trackable_on_etsy"=>1],
	"pos-indonesia"=>["Pos Indonesia","trackable_on_etsy"=>1],
	"pos-indonesia-int"=>["Pos Indonesia International","trackable_on_etsy"=>1],
	"malaysia-post"=>["Pos Malaysia","trackable_on_etsy"=>1],
	"post-aruba"=>["Post Aruba","trackable_on_etsy"=>0],
	"post-fiji"=>["Post Fiji","trackable_on_etsy"=>0],
	"post-luxembourg"=>["Post Luxembourg","trackable_on_etsy"=>0],
	"postnl"=>["PostNL Domestic","trackable_on_etsy"=>1],
	"postnl-international"=>["PostNL International","trackable_on_etsy"=>1],
	"postnl-3s"=>["PostNL International 3S","trackable_on_etsy"=>1],
	"danmark-post"=>["PostNord","trackable_on_etsy"=>1],
	"postnord"=>["PostNord Logistics","trackable_on_etsy"=>1],
	"posta"=>["Posta","trackable_on_etsy"=>0],
	"posta-kenya"=>["Posta Kenya","trackable_on_etsy"=>0],
	"posta-moldovei"=>["Posta Moldovei","trackable_on_etsy"=>0],
	"posta-romana"=>["Posta Romana","trackable_on_etsy"=>1],
	"posta-shqiptare"=>["Posta Shqiptare","trackable_on_etsy"=>0],
	"posta-slovenije"=>["Posta Slovenije","trackable_on_etsy"=>0],
	"posta-srbije"=>["Posta Srbije","trackable_on_etsy"=>0],
	"posta-uganda"=>["Posta Uganda","trackable_on_etsy"=>0],
	"poste-italiane"=>["Poste Italiane","trackable_on_etsy"=>1],
	"poste-italiane-paccocelere"=>["Poste Italiane Paccocelere","trackable_on_etsy"=>1],
	"poste-maroc"=>["Poste Maroc","trackable_on_etsy"=>0],
	"sweden-posten"=>["Posten AB","trackable_on_etsy"=>1],
	"posten-norge"=>["Posten Norge","trackable_on_etsy"=>1],
	"posti"=>["Posti","trackable_on_etsy"=>1],
	"postmates"=>["Postmates","trackable_on_etsy"=>1],
	"purolator"=>["Purolator","trackable_on_etsy"=>1],
	"qatar-post"=>["Qatar Post","trackable_on_etsy"=>0],
	"rl-carriers"=>["RL Carriers","trackable_on_etsy"=>1],
	"rpx"=>["RPX Indonesia","trackable_on_etsy"=>1],
	"red-express"=>["Red Express","trackable_on_etsy"=>1],
	"mexico-redpack"=>["Redpack","trackable_on_etsy"=>1],
	"royal-mail"=>["Royal Mail","trackable_on_etsy"=>0],
	"russian-post"=>["Russian Post","trackable_on_etsy"=>1],
	"sfb2c"=>["S.F International","trackable_on_etsy"=>1],
	"italy-sda"=>["SDA Express Courier","trackable_on_etsy"=>1],
	"spanish-seur"=>["SEUR Espana (Domestico)","trackable_on_etsy"=>1],
	"portugal-seur"=>["SEUR Portugal (Domestico)","trackable_on_etsy"=>1],
	"sf-express"=>["SF Express","trackable_on_etsy"=>1],
	"safexpress"=>["Safexpress","trackable_on_etsy"=>1],
	"sagawa"=>["Sagawa","trackable_on_etsy"=>1],
	"saudi-post"=>["Saudi Post","trackable_on_etsy"=>1],
	"selektvracht"=>["Selektvracht","trackable_on_etsy"=>1],
	"mexico-senda-express"=>["Senda Express","trackable_on_etsy"=>1],
	"sendle"=>["Sendle","trackable_on_etsy"=>1],
	"serpost"=>["Serpost","trackable_on_etsy"=>0],
	"singapore-post"=>["Singapore Post","trackable_on_etsy"=>1],
	"singapore-speedpost"=>["Singapore SpeedPost","trackable_on_etsy"=>1],
	"siodemka"=>["Siodemka","trackable_on_etsy"=>1],
	"skynetworldwide"=>["SkyNet Wordwide Express","trackable_on_etsy"=>1],
	"skynet-malaysia"=>["Skynet Malaysia","trackable_on_etsy"=>1],
	"skynetworldwide"=>["Skynet Worldwide Express","trackable_on_etsy"=>1],
	"slovenska-posta"=>["Slovenska posta","trackable_on_etsy"=>0],
	"sapo"=>["South Africa Post Office","trackable_on_etsy"=>1],
	"star-track"=>["StarTrack","trackable_on_etsy"=>1],
	"swiss-post"=>["Swiss Post","trackable_on_etsy"=>1],
	"taqbin-hk"=>["TA-Q-BIN Hong Kong","trackable_on_etsy"=>1],
	"taqbin-jp"=>["TA-Q-BIN Japan","trackable_on_etsy"=>1],
	"taqbin-my"=>["TA-Q-BIN Malaysia","trackable_on_etsy"=>1],
	"taqbin-sg"=>["TA-Q-BIN Singapore","trackable_on_etsy"=>1],
	"tgx"=>["TGX","trackable_on_etsy"=>1],
	"tnt"=>["TNT","trackable_on_etsy"=>1],
	"tnt-au"=>["TNT Australia","trackable_on_etsy"=>1],
	"tnt-fr"=>["TNT France","trackable_on_etsy"=>1],
	"tnt-it"=>["TNT Italia","trackable_on_etsy"=>1],
	"tnt-uk"=>["TNT UK","trackable_on_etsy"=>1],
	"ttpost"=>["TTPost","trackable_on_etsy"=>0],
	"thailand-post"=>["Thailand Post","trackable_on_etsy"=>1],
	"toll-global-express"=>["Toll Global Express","trackable_on_etsy"=>0],
	"toll-priority"=>["Toll Priority","trackable_on_etsy"=>1],
	"uk-mail"=>["UK Mail","trackable_on_etsy"=>1],
	"ups"=>["UPS","trackable_on_etsy"=>1],
	"ups-freight"=>["UPS Freight","trackable_on_etsy"=>1],
	"usps"=>["USPS","trackable_on_etsy"=>1],
	"ukrposhta"=>["UkrPoshta","trackable_on_etsy"=>1],
	"vanuatu-post"=>["Vanuatu Post","trackable_on_etsy"=>0],
	"vnpost"=>["Vietnam Post","trackable_on_etsy"=>1],
	"vnpost-ems"=>["Vietnam Post EMS","trackable_on_etsy"=>1],
	"whistl"=>["Whistl","trackable_on_etsy"=>1],
	"xend"=>["Xend","trackable_on_etsy"=>1],
	"yrc"=>["YRC Freight","trackable_on_etsy"=>1],
	"yanwen"=>["Yanwen","trackable_on_etsy"=>1],
	"yemen-post"=>["Yemen Post","trackable_on_etsy"=>0],
	"yodel"=>["Yodel","trackable_on_etsy"=>1],
	"yodel-international"=>["Yodel International","trackable_on_etsy"=>1],
	"zampost"=>["Zampost","trackable_on_etsy"=>0],
	"zimpost"=>["Zimpost","trackable_on_etsy"=>0],
	"i-parcel"=>["i-parcel","trackable_on_etsy"=>1],
	"myhermes-uk"=>["myHermes UK","trackable_on_etsy"=>1],
];